version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gate-qris?schema=public
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
      - LOG_FILE_PATH=/var/log/gate-qris/access.log
    depends_on:
      - db
    restart: always
    volumes:
      - ./logs:/var/log/gate-qris
    networks:
      - gate-qris-network

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gate-qris
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gate-qris-network

volumes:
  postgres_data:

networks:
  gate-qris-network:
